services:
  db:
    image: postgres:16-bullseye
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${APP_PORT}:8888
    depends_on:
      - db

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - ${ADMIN_PORT}:8080
